 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bibliographic_descriptions", type: :request do
  # BibliographicDescription. As you add validations to BibliographicDescription, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BibliographicDescription.create! valid_attributes
      get bibliographic_descriptions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bibliographic_description = BibliographicDescription.create! valid_attributes
      get bibliographic_description_url(bibliographic_description)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bibliographic_description_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      bibliographic_description = BibliographicDescription.create! valid_attributes
      get edit_bibliographic_description_url(bibliographic_description)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BibliographicDescription" do
        expect {
          post bibliographic_descriptions_url, params: { bibliographic_description: valid_attributes }
        }.to change(BibliographicDescription, :count).by(1)
      end

      it "redirects to the created bibliographic_description" do
        post bibliographic_descriptions_url, params: { bibliographic_description: valid_attributes }
        expect(response).to redirect_to(bibliographic_description_url(BibliographicDescription.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BibliographicDescription" do
        expect {
          post bibliographic_descriptions_url, params: { bibliographic_description: invalid_attributes }
        }.to change(BibliographicDescription, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bibliographic_descriptions_url, params: { bibliographic_description: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bibliographic_description" do
        bibliographic_description = BibliographicDescription.create! valid_attributes
        patch bibliographic_description_url(bibliographic_description), params: { bibliographic_description: new_attributes }
        bibliographic_description.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bibliographic_description" do
        bibliographic_description = BibliographicDescription.create! valid_attributes
        patch bibliographic_description_url(bibliographic_description), params: { bibliographic_description: new_attributes }
        bibliographic_description.reload
        expect(response).to redirect_to(bibliographic_description_url(bibliographic_description))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bibliographic_description = BibliographicDescription.create! valid_attributes
        patch bibliographic_description_url(bibliographic_description), params: { bibliographic_description: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bibliographic_description" do
      bibliographic_description = BibliographicDescription.create! valid_attributes
      expect {
        delete bibliographic_description_url(bibliographic_description)
      }.to change(BibliographicDescription, :count).by(-1)
    end

    it "redirects to the bibliographic_descriptions list" do
      bibliographic_description = BibliographicDescription.create! valid_attributes
      delete bibliographic_description_url(bibliographic_description)
      expect(response).to redirect_to(bibliographic_descriptions_url)
    end
  end
end
